language: node_js
node_js:
  - "15"
dist: bionic
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli@12

script:
  - ng lint
  - ng build --configuration production --base-href /restaurantes-app/
  - cd dist/restaurantes-app
  - cp index.html 404.html
  - cd ../..

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/restaurantes-app
  on:
    branch: master
